#!/bin/bash
# first time setup script for n-i-x wrappers
# creates directory and git commits in $HOME/.config/n-i-x/
set -e

echo "installing n-i-x scripts to /usr/bin/"
sudo cp -f *n-i-x* /usr/bin/
echo "success!"

echo "creating $HOME/.config/n-i-x/"
mkdir -p $HOME/.config/n-i-x/
echo "success!"

DIR=$PWD

echo "saving nix manifest"
touch $HOME/.config/n-i-x/manifest.json
cd $HOME/.config/n-i-x && git init && git branch -m master && git add . && git commit -m "initial commit (created by n-i-x install_script)"
$DIR/n-i-x-save_new_manifest save manifest.json
echo "success!"
