#!/bin/bash
set -e

MANIFEST_PATH="/home/valar/projects/n-i-x/manifest.json"

echo "currently installed packages:"
jq '.[] | .[] | .attrPath' $MANIFEST_PATH 2>/dev/null | sed 's/legacyPackages.x86_64-linux.//g' | jq

